### PR TITLE
Update xortool

### PR DESCRIPTION
**Pull request by adi1998**
Making this change is the only way I was able to get it to run on my Ubuntu 16.04.

### CODE REVIEW

**Comment by hellman** [comment]
I don't get it. Are you sure you don't have multiple xortool installed? parse_parameters' arguments are not optional..

**Comment by adi1998** [comment]
[https://pastebin.com/NUagTKv2](url) i don't think that's the case

**Comment by xtaran** [comment]
JFTR: This tool works fine for me on Debian Stable (Debian 9.x Stretch as of today) which has been released after Ubuntu 16.04.

**Comment by hellman** [comment]
Please reopen if this is relevant.

**Comment by hellman** [comment]
Ah, I see what may be the problem. The pip version is old and has no __version__. If you run ./xortool from the xortool folder then it imports the old version. So to run the cloned version you need to run xortool from level up, i.e. ./xortool/xortool so that it imports the new package. Anyway, I should update pip version soon.

**Pull request closed without merging**
